### ISSUE TITLE
Please add an easy API: isMute()

### ISSUE THREAD

**Issue by jerryzooyoyo** [Leo3418/RealMute#1]
This is a great plugin.
I want to use this muting system to make some plugin.
Here is the API I want to:
`$this->mute=$this->getServer()->getPluginManager()->getPlugin("RealMute");` 
`if($this->mute->isMute($player)) {bla bla bla }`
Hope you can add such an easy API for coding.

**Comment by Leo3418** [comment]
Thanks for the suggestion. I will try that.

**Comment by jerryzooyoyo** [comment]
When I used isMuted($player), here is a problem I met.
- When the player has been muted, he or she can change the account and pass the muting system.

Already enabled the mutedevice.

Can you add these to the API ? ( Player A has been muted. )
- Player A used the account Player B to join the server, isMuted($playerB) still return true.
- If "muteall", isMuted($anyplayer) return true.
- If Player A is auto-muted, isMuted($playerA) return true.

Or add other APIs.
Thanks.^_^

**Comment by Leo3418** [comment]
> Player A used the account Player B to join the server, isMuted($playerB) still return true.

I will add it.

> If "muteall", isMuted($anyplayer) return true.

Because muting all players will not affect individual player's settings, I don't want to implement it. However, you may use `$this->mute->getConfig()->get($muteall)` in your plugin, or edit source code of this plugin instead. (GPLv3 does not require you to release modified source code unless you redistribute it)

> If Player A is auto-muted, isMuted($playerA) return true.

I think it is already fulfilled.

**Comment by jerryzooyoyo** [comment]
Point 1 : Thank you !
Point 2 : Ok. I will try.
Point 3 : Tested. Already have. Thanks.
